name: Build and Test Java Gradle
on:
  push:
    branches:
      - master
permissions:
  contents: read
  
jobs:
  my_first_job:
    runs-on: windows-latest
    steps:
      - name: Repo cloning
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Biuld with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
